import { MigrationInterface, QueryRunner } from 'typeorm'

export class IdxBigintUpdate1621105396496 implements MigrationInterface {
    name = 'IdxBigintUpdate1621105396496'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("DROP INDEX `Agent_UN_1` ON `Agent`");
        await queryRunner.query("DROP INDEX `Agent_UN_2` ON `Agent`");
        await queryRunner.query("DROP INDEX `Agent_UN_3` ON `Agent`");
        await queryRunner.query("DROP INDEX `ModuleReason_FK` ON `ModuleReason`");
        await queryRunner.query("DROP INDEX `User_FK` ON `OfficeUser`");
        await queryRunner.query("DROP INDEX `Options_FK` ON `Options`");
        await queryRunner.query("DROP INDEX `payment_agent_id_idx` ON `Payment`");
        await queryRunner.query("DROP INDEX `payment_application_id_idx` ON `Payment`");
        await queryRunner.query("DROP INDEX `payment_client_id_idx` ON `Payment`");
        await queryRunner.query("DROP INDEX `payment_doc_id_idx` ON `Payment`");
        await queryRunner.query("DROP INDEX `payment_info_id_idx` ON `Payment`");
        await queryRunner.query("DROP INDEX `payment_order_no_idx` ON `Payment`");
        await queryRunner.query("DROP INDEX `fund_id_UNIQUE` ON `Recommendation`");
        await queryRunner.query("DROP INDEX `account_no` ON `UTAccount`");
        await queryRunner.query("DROP INDEX `uta_client_id_idx` ON `UTAccount`");
        await queryRunner.query("DROP INDEX `UTAccount_FK_1` ON `UTAccount`");
        // await queryRunner.query("ALTER TABLE `Agent` ADD UNIQUE INDEX `IDX_bd0aac431ed1187ca6d1fb60a8` (`nric`)");
        await queryRunner.query("ALTER TABLE `AuditLog` CHANGE `status` `status` varchar(20) NULL");
        await queryRunner.query("ALTER TABLE `CaseTracker` CHANGE `status` `status` varchar(20) NOT NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `charge_fee_id` `charge_fee_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `charge_fee_id` `charge_fee_id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("DROP INDEX `Client_IDX_3` ON `Client`");
        await queryRunner.query("ALTER TABLE `Client` CHANGE `master_client_id` `master_client_id` int NULL");
        await queryRunner.query("ALTER TABLE `FundDocument` CHANGE `remark` `remark` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `Investment` CHANGE `status_id` `status_id` int NULL DEFAULT '1'");
        await queryRunner.query("ALTER TABLE `ModuleReason` DROP PRIMARY KEY");
        // await queryRunner.query("ALTER TABLE `ModuleReason` ADD PRIMARY KEY (`reason_id`)");
        // await queryRunner.query("ALTER TABLE `ModuleReason` DROP COLUMN `module_id`");
        await queryRunner.query("ALTER TABLE `ModuleReason` CHANGE `module_id` `module_id` int NOT NULL");
        // await queryRunner.query("ALTER TABLE `ModuleReason` DROP PRIMARY KEY");
        // await queryRunner.query("ALTER TABLE `ModuleReason` ADD PRIMARY KEY (`reason_id`, `module_id`)");
        // await queryRunner.query("ALTER TABLE `ModuleReason` DROP PRIMARY KEY");
        // await queryRunner.query("ALTER TABLE `ModuleReason` ADD PRIMARY KEY (`module_id`)");
        // await queryRunner.query("ALTER TABLE `ModuleReason` DROP COLUMN `reason_id`");
        await queryRunner.query("ALTER TABLE `ModuleReason` CHANGE `reason_id` `reason_id` int NOT NULL");
        // await queryRunner.query("ALTER TABLE `ModuleReason` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `ModuleReason` ADD PRIMARY KEY (`module_id`, `reason_id`)");
        await queryRunner.query("ALTER TABLE `Nominee` CHANGE `id_number` `id_number` varchar(20) NOT NULL");
        await queryRunner.query("ALTER TABLE `OfficeUser` CHANGE `status` `status` varchar(20) NULL DEFAULT 'PENDING'");
        await queryRunner.query("ALTER TABLE `OfficeUser` CHANGE `remarks` `remarks` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `Options` CHANGE `option_id` `option_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `Options` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `Options` CHANGE `option_id` `option_id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Options` CHANGE `question_id` `question_id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `Payment` CHANGE `payment_id` `payment_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `Payment` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `Payment` CHANGE `payment_id` `payment_id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Payment` CHANGE `application_id` `application_id` int NULL");
        await queryRunner.query("ALTER TABLE `Payment` CHANGE `payment_info_id` `payment_info_id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `Payment` CHANGE `status` `status` varchar(20) NOT NULL DEFAULT 'Pending'");
        await queryRunner.query("ALTER TABLE `PaymentInfo` CHANGE `payment_info_id` `payment_info_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `PaymentInfo` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `PaymentInfo` CHANGE `payment_info_id` `payment_info_id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `PaymentInfo` CHANGE `kib_bank_name` `kib_bank_name` varchar(150) NULL");
        await queryRunner.query("ALTER TABLE `PaymentInfo` CHANGE `client_name` `client_name` varchar(150) NULL");
        await queryRunner.query("ALTER TABLE `PaymentInfo` CHANGE `bank_account_name` `bank_account_name` varchar(150) NULL");
        await queryRunner.query("ALTER TABLE `Recommendation` CHANGE `fund_currency` `fund_currency` varchar(5) NULL");
        // await queryRunner.query("ALTER TABLE `RedemptionFee` ADD UNIQUE INDEX `IDX_bcbe3c2abb4fd8a29a1571a1be` (`fund_id`)");
        await queryRunner.query("CREATE UNIQUE INDEX `Agent_UN_2` ON `Agent` (`email`)");
        await queryRunner.query("CREATE UNIQUE INDEX `Agent_UN_1` ON `Agent` (`nric`)");
        await queryRunner.query("CREATE INDEX `Client_IDX_3` ON `Client` (`master_client_id`)");
        await queryRunner.query("CREATE INDEX `OfficeUser_IDX_2` ON `OfficeUser` (`user_group_role_id`)");
        await queryRunner.query("CREATE INDEX `OfficeUser_IDX_1` ON `OfficeUser` (`username`)");
        await queryRunner.query("CREATE INDEX `Options_IDX_1` ON `Options` (`question_id`)");
        await queryRunner.query("CREATE INDEX `Payment_IDX_2` ON `Payment` (`agent_id`)");
        await queryRunner.query("CREATE INDEX `Payment_IDX_1` ON `Payment` (`order_no`)");
        await queryRunner.query("CREATE UNIQUE INDEX `RedemptionFee_IDX_1` ON `RedemptionFee` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `SeenClick_IDX_1` ON `SeenClick` (`seen_by`)");
        await queryRunner.query("CREATE INDEX `SeenDashboard_IDX_1` ON `SeenDashboard` (`seen_by`)");
        await queryRunner.query("CREATE INDEX `SocketUser_IDX_1` ON `SocketUser` (`username`)");
        await queryRunner.query("CREATE INDEX `StatusTracker_IDX_2` ON `StatusTracker` (`username`)");
        await queryRunner.query("CREATE INDEX `StatusTracker_IDX_1` ON `StatusTracker` (`user_id`)");
        await queryRunner.query("CREATE INDEX `SwitchCheck_IDX_1` ON `SwitchCheck` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `SwitchFee_IDX_1` ON `SwitchFee` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `SwitchMultiple_IDX_1` ON `SwitchMultiple` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `TransactionReason_IDX_1` ON `TransactionReason` (`category`)");
        await queryRunner.query("CREATE INDEX `TransferFee_IDX_1` ON `TransferFee` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `UTAccount_IDX_3` ON `UTAccount` (`joint_id`)");
        await queryRunner.query("CREATE INDEX `UTAccount_IDX_2` ON `UTAccount` (`client_id`)");
        await queryRunner.query("CREATE INDEX `UTAccount_IDX_1` ON `UTAccount` (`account_no`)");
        await queryRunner.query("CREATE INDEX `Utmc_IDX_1` ON `Utmc` (`fund_holiday_id`)");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("DROP INDEX `Utmc_IDX_1` ON `Utmc`");
        await queryRunner.query("DROP INDEX `UTAccount_IDX_1` ON `UTAccount`");
        await queryRunner.query("DROP INDEX `UTAccount_IDX_2` ON `UTAccount`");
        await queryRunner.query("DROP INDEX `UTAccount_IDX_3` ON `UTAccount`");
        await queryRunner.query("DROP INDEX `TransferFee_IDX_1` ON `TransferFee`");
        await queryRunner.query("DROP INDEX `TransactionReason_IDX_1` ON `TransactionReason`");
        await queryRunner.query("DROP INDEX `SwitchMultiple_IDX_1` ON `SwitchMultiple`");
        await queryRunner.query("DROP INDEX `SwitchFee_IDX_1` ON `SwitchFee`");
        await queryRunner.query("DROP INDEX `SwitchCheck_IDX_1` ON `SwitchCheck`");
        await queryRunner.query("DROP INDEX `StatusTracker_IDX_1` ON `StatusTracker`");
        await queryRunner.query("DROP INDEX `StatusTracker_IDX_2` ON `StatusTracker`");
        await queryRunner.query("DROP INDEX `StatusTracker_IDX_3` ON `StatusTracker`");
        await queryRunner.query("DROP INDEX `SocketUser_IDX_1` ON `SocketUser`");
        await queryRunner.query("DROP INDEX `SeenDashboard_IDX_1` ON `SeenDashboard`");
        await queryRunner.query("DROP INDEX `SeenClick_IDX_1` ON `SeenClick`");
        await queryRunner.query("DROP INDEX `RedemptionFee_IDX_1` ON `RedemptionFee`");
        await queryRunner.query("DROP INDEX `Payment_IDX_1` ON `Payment`");
        await queryRunner.query("DROP INDEX `Payment_IDX_2` ON `Payment`");
        await queryRunner.query("DROP INDEX `Options_IDX_1` ON `Options`");
        await queryRunner.query("DROP INDEX `OfficeUser_IDX_1` ON `OfficeUser`");
        await queryRunner.query("DROP INDEX `OfficeUser_IDX_2` ON `OfficeUser`");
        await queryRunner.query("DROP INDEX `Client_IDX_3` ON `Client`");
        await queryRunner.query("DROP INDEX `Agent_UN_1` ON `Agent`");
        await queryRunner.query("DROP INDEX `Agent_UN_2` ON `Agent`");
        await queryRunner.query("ALTER TABLE `RedemptionFee` DROP INDEX `IDX_bcbe3c2abb4fd8a29a1571a1be`");
        await queryRunner.query("ALTER TABLE `Recommendation` DROP COLUMN `fund_currency`");
        await queryRunner.query("ALTER TABLE `Recommendation` ADD `fund_currency` varchar(20) NULL");
        await queryRunner.query("ALTER TABLE `PaymentInfo` DROP COLUMN `bank_account_name`");
        await queryRunner.query("ALTER TABLE `PaymentInfo` ADD `bank_account_name` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `PaymentInfo` DROP COLUMN `client_name`");
        await queryRunner.query("ALTER TABLE `PaymentInfo` ADD `client_name` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `PaymentInfo` DROP COLUMN `kib_bank_name`");
        await queryRunner.query("ALTER TABLE `PaymentInfo` ADD `kib_bank_name` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `PaymentInfo` DROP COLUMN `payment_info_id`");
        await queryRunner.query("ALTER TABLE `PaymentInfo` ADD `payment_info_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `PaymentInfo` ADD PRIMARY KEY (`payment_info_id`)");
        await queryRunner.query("ALTER TABLE `PaymentInfo` CHANGE `payment_info_id` `payment_info_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Payment` DROP COLUMN `status`");
        await queryRunner.query("ALTER TABLE `Payment` ADD `status` varchar(10) NOT NULL DEFAULT 'Pending'");
        await queryRunner.query("ALTER TABLE `Payment` DROP COLUMN `payment_info_id`");
        await queryRunner.query("ALTER TABLE `Payment` ADD `payment_info_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `Payment` DROP COLUMN `application_id`");
        await queryRunner.query("ALTER TABLE `Payment` ADD `application_id` bigint NULL");
        await queryRunner.query("ALTER TABLE `Payment` DROP COLUMN `payment_id`");
        await queryRunner.query("ALTER TABLE `Payment` ADD `payment_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Payment` ADD PRIMARY KEY (`payment_id`)");
        await queryRunner.query("ALTER TABLE `Payment` CHANGE `payment_id` `payment_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Options` DROP COLUMN `question_id`");
        await queryRunner.query("ALTER TABLE `Options` ADD `question_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `Options` DROP COLUMN `option_id`");
        await queryRunner.query("ALTER TABLE `Options` ADD `option_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Options` ADD PRIMARY KEY (`option_id`)");
        await queryRunner.query("ALTER TABLE `Options` CHANGE `option_id` `option_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `OfficeUser` DROP COLUMN `remarks`");
        await queryRunner.query("ALTER TABLE `OfficeUser` ADD `remarks` varchar(20) NULL");
        await queryRunner.query("ALTER TABLE `OfficeUser` DROP COLUMN `status`");
        await queryRunner.query("ALTER TABLE `OfficeUser` ADD `status` varchar(255) NULL DEFAULT 'PENDING'");
        await queryRunner.query("ALTER TABLE `Nominee` DROP COLUMN `id_number`");
        await queryRunner.query("ALTER TABLE `Nominee` ADD `id_number` varchar(15) NOT NULL");
        await queryRunner.query("ALTER TABLE `ModuleReason` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `ModuleReason` ADD PRIMARY KEY (`module_id`)");
        await queryRunner.query("ALTER TABLE `ModuleReason` DROP COLUMN `reason_id`");
        await queryRunner.query("ALTER TABLE `ModuleReason` ADD `reason_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `ModuleReason` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `ModuleReason` ADD PRIMARY KEY (`reason_id`, `module_id`)");
        await queryRunner.query("ALTER TABLE `ModuleReason` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `ModuleReason` ADD PRIMARY KEY (`reason_id`)");
        await queryRunner.query("ALTER TABLE `ModuleReason` DROP COLUMN `module_id`");
        await queryRunner.query("ALTER TABLE `ModuleReason` ADD `module_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `ModuleReason` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `ModuleReason` ADD PRIMARY KEY (`module_id`, `reason_id`)");
        await queryRunner.query("ALTER TABLE `Investment` DROP COLUMN `status_id`");
        await queryRunner.query("ALTER TABLE `Investment` ADD `status_id` bigint NULL DEFAULT '1'");
        await queryRunner.query("ALTER TABLE `FundDocument` DROP COLUMN `remark`");
        await queryRunner.query("ALTER TABLE `FundDocument` ADD `remark` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `Client` DROP COLUMN `master_client_id`");
        await queryRunner.query("ALTER TABLE `Client` ADD `master_client_id` bigint NULL");
        await queryRunner.query("CREATE INDEX `Client_IDX_3` ON `Client` (`master_client_id`)");
        await queryRunner.query("ALTER TABLE `ChargeFee` DROP COLUMN `charge_fee_id`");
        await queryRunner.query("ALTER TABLE `ChargeFee` ADD `charge_fee_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `ChargeFee` ADD PRIMARY KEY (`charge_fee_id`)");
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `charge_fee_id` `charge_fee_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `CaseTracker` DROP COLUMN `status`");
        await queryRunner.query("ALTER TABLE `CaseTracker` ADD `status` varchar(100) NOT NULL");
        await queryRunner.query("ALTER TABLE `AuditLog` DROP COLUMN `status`");
        await queryRunner.query("ALTER TABLE `AuditLog` ADD `status` varchar(30) NULL");
        await queryRunner.query("ALTER TABLE `Agent` DROP INDEX `IDX_bd0aac431ed1187ca6d1fb60a8`");
        await queryRunner.query("CREATE INDEX `UTAccount_FK_1` ON `UTAccount` (`joint_id`)");
        await queryRunner.query("CREATE INDEX `uta_client_id_idx` ON `UTAccount` (`client_id`)");
        await queryRunner.query("CREATE INDEX `account_no` ON `UTAccount` (`account_no`)");
        await queryRunner.query("CREATE UNIQUE INDEX `fund_id_UNIQUE` ON `Recommendation` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `payment_order_no_idx` ON `Payment` (`order_no`)");
        await queryRunner.query("CREATE INDEX `payment_info_id_idx` ON `Payment` (`payment_info_id`)");
        await queryRunner.query("CREATE INDEX `payment_doc_id_idx` ON `Payment` (`doc_id`)");
        await queryRunner.query("CREATE INDEX `payment_client_id_idx` ON `Payment` (`client_id`)");
        await queryRunner.query("CREATE INDEX `payment_application_id_idx` ON `Payment` (`application_id`)");
        await queryRunner.query("CREATE INDEX `payment_agent_id_idx` ON `Payment` (`agent_id`)");
        await queryRunner.query("CREATE INDEX `Options_FK` ON `Options` (`question_id`)");
        await queryRunner.query("CREATE INDEX `User_FK` ON `OfficeUser` (`user_group_role_id`)");
        await queryRunner.query("CREATE INDEX `ModuleReason_FK` ON `ModuleReason` (`reason_id`)");
        await queryRunner.query("CREATE UNIQUE INDEX `Agent_UN_3` ON `Agent` (`email`)");
        await queryRunner.query("CREATE UNIQUE INDEX `Agent_UN_2` ON `Agent` (`nric`)");
        await queryRunner.query("CREATE UNIQUE INDEX `Agent_UN_1` ON `Agent` (`agent_id`)");
    }

}
