import { MigrationInterface, QueryRunner } from 'typeorm'

export class test1621000691280 implements MigrationInterface {
    name = 'test1621000691280'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `CaseTracker` DROP FOREIGN KEY `FK_90c445a2765f361ee0cc39ad8e0`");
        await queryRunner.query("ALTER TABLE `Client` DROP FOREIGN KEY `FK_54aea71963d14571999cfe0c9f1`");
        await queryRunner.query("ALTER TABLE `ClientAssessment` DROP FOREIGN KEY `FK_9e6d44751031215c43039ae2e23`");
        await queryRunner.query("ALTER TABLE `Document` DROP FOREIGN KEY `FK_610236cf8c9a02e9d17f9f95029`");
        await queryRunner.query("ALTER TABLE `Edd` DROP FOREIGN KEY `FK_7a21ad29d65d05eb9e2e0a4451e`");
        await queryRunner.query("ALTER TABLE `Edd` DROP FOREIGN KEY `FK_95fb95debbf9a58635ad43ae164`");
        await queryRunner.query("ALTER TABLE `Edd` DROP FOREIGN KEY `FK_a0bbbc43b70b5b3120efb9d4287`");
        await queryRunner.query("ALTER TABLE `EddCase` DROP FOREIGN KEY `FK_0a8a3c2b9543efbb396f5e930e1`");
        await queryRunner.query("ALTER TABLE `EddCase` DROP FOREIGN KEY `FK_31382fce5e0b940da02602f453c`");
        await queryRunner.query("ALTER TABLE `EddCase` DROP FOREIGN KEY `FK_4ed223c8a4beb795e0b19dc185b`");
        await queryRunner.query("ALTER TABLE `EddCase` DROP FOREIGN KEY `FK_8f98dc8bf3579c4c1be800cb96d`");
        await queryRunner.query("ALTER TABLE `EddCase` DROP FOREIGN KEY `FK_cd3b4f4ea7bc0dea21c9dd28cea`");
        await queryRunner.query("ALTER TABLE `Investment` DROP FOREIGN KEY `FK_e9f1de495fc04601028b81a6bf2`");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` DROP FOREIGN KEY `FK_037a4d901b8cd5067bb1401d1b3`");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` DROP FOREIGN KEY `FK_a4c066f2a6fdf44dd02e6c0660b`");
        await queryRunner.query("ALTER TABLE `ModuleReason` DROP FOREIGN KEY `FK_0169d301a545068bc54016bad34`");
        await queryRunner.query("ALTER TABLE `ModuleReason` DROP FOREIGN KEY `FK_fa3cad0cd2a73b35cf1b940ddc8`");
        await queryRunner.query("ALTER TABLE `OfficeUser` DROP FOREIGN KEY `FK_3c6be3e17ee091aefcbf119d46e`");
        await queryRunner.query("ALTER TABLE `Payment` DROP FOREIGN KEY `FK_823c82b9e2ce11ccad66e36b2ce`");
        await queryRunner.query("ALTER TABLE `Payment` DROP FOREIGN KEY `FK_9c6d107c5e1ddb80e81b821b179`");
        await queryRunner.query("ALTER TABLE `UTAccount` DROP FOREIGN KEY `FK_e6d3bf66e5a97fc5adac7f4ffb2`");
        await queryRunner.query("DROP INDEX `agent_id_UNIQUE` ON `Agent`");
        await queryRunner.query("DROP INDEX `Email_UN` ON `Agent`");
        await queryRunner.query("DROP INDEX `fa_code_UNIQUE` ON `Agent`");
        await queryRunner.query("DROP INDEX `CaseTracker_FK` ON `CaseTracker`");
        await queryRunner.query("DROP INDEX `CaseTracker_FK_1` ON `CaseTracker`");
        await queryRunner.query("DROP INDEX `client_id_fk` ON `Client`");
        await queryRunner.query("DROP INDEX `joint_client_fk_idx` ON `Client`");
        await queryRunner.query("DROP INDEX `client_id` ON `ClientAssessment`");
        await queryRunner.query("DROP INDEX `client_id_UNIQUE` ON `ClientAssessment`");
        await queryRunner.query("DROP INDEX `REL_9e6d44751031215c43039ae2e2` ON `ClientAssessment`");
        await queryRunner.query("DROP INDEX `risk_score` ON `ClientAssessment`");
        await queryRunner.query("DROP INDEX `doc_client_id` ON `Document`");
        await queryRunner.query("DROP INDEX `doct_id` ON `Document`");
        await queryRunner.query("DROP INDEX `Edd_FK` ON `Edd`");
        await queryRunner.query("DROP INDEX `Edd_FK_2` ON `Edd`");
        await queryRunner.query("DROP INDEX `Edd_FK_3` ON `Edd`");
        await queryRunner.query("DROP INDEX `EddCase_FK` ON `EddCase`");
        await queryRunner.query("DROP INDEX `EddCase_FK_1` ON `EddCase`");
        await queryRunner.query("DROP INDEX `EddCase_FK_2` ON `EddCase`");
        await queryRunner.query("DROP INDEX `EddCase_FK_4` ON `EddCase`");
        await queryRunner.query("DROP INDEX `EddCase_FK_5` ON `EddCase`");
        await queryRunner.query("DROP INDEX `EddCase_UN` ON `EddCase`");
        await queryRunner.query("DROP INDEX `Investment_FK_1` ON `Investment`");
        await queryRunner.query("DROP INDEX `Investment_FK_2` ON `Investment`");
        await queryRunner.query("DROP INDEX `master_client_id` ON `MasterClient`");
        await queryRunner.query("DROP INDEX `ModuleQuestion_FK` ON `ModuleQuestion`");
        await queryRunner.query("ALTER TABLE `DefaultUnit` ADD `display_name` varchar(100) NOT NULL");
        // await queryRunner.query("ALTER TABLE `FundDocument` ADD `file_type` varchar(20) NULL");
        // await queryRunner.query("ALTER TABLE `FundHoliday` ADD `name` varchar(50) NOT NULL");
        await queryRunner.query("ALTER TABLE `Agent` CHANGE `agent_id` `agent_id` binary(16) NOT NULL");
        // await queryRunner.query("ALTER TABLE `Agent` ADD UNIQUE INDEX `IDX_04bbcf1b15f36b382c0aa749c2` (`agent_id`)");
        await queryRunner.query("ALTER TABLE `Agent` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Agent` CHANGE `agent_code` `agent_code` varchar(20) NULL");
        await queryRunner.query("ALTER TABLE `Agent` CHANGE `nric` `nric` varchar(16) NOT NULL");
        // await queryRunner.query("ALTER TABLE `Agent` ADD UNIQUE INDEX `IDX_bd0aac431ed1187ca6d1fb60a8` (`nric`)");
        await queryRunner.query("ALTER TABLE `Agent` CHANGE `agency` `agency` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `Agent` CHANGE `timestamp` `timestamp` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `Application` CHANGE `uta_id` `uta_id` binary(16) NULL");
        await queryRunner.query("ALTER TABLE `AuditLog` CHANGE `request_id` `request_id` bigint NULL");
        await queryRunner.query("ALTER TABLE `Branch` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Branch` CHANGE `state` `state` varchar(50) NULL");
        await queryRunner.query("ALTER TABLE `Branch` CHANGE `code` `code` varchar(50) NULL");
        await queryRunner.query("ALTER TABLE `Branch` CHANGE `timestamp` `timestamp` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `CaseTracker` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `CaseTracker` CHANGE `case_id` `case_id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `CaseTracker` CHANGE `remark` `remark` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `charge_fee_id` `charge_fee_id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `charge_fee_id` `charge_fee_id` bigint NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `exit_epf_value` `exit_epf_value` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `exit_epf_percentage` `exit_epf_percentage` varchar(100) NULL");       
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `exit_non_epf_value` `exit_non_epf_value` varchar(100) NULL");        
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `exit_non_epf_percentage` `exit_non_epf_percentage` varchar(100) NULL");       
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `min_sales_fee_epf` `min_sales_fee_epf` varchar(100) NULL");       
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `max_sales_fee_epf` `max_sales_fee_epf` varchar(100) NULL");        
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `min_sales_fee_non_epf` `min_sales_fee_non_epf` varchar(100) NULL");        
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `max_sales_fee_non_epf` `max_sales_fee_non_epf` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `Client` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Client` CHANGE `salutation` `salutation` varchar(15) NULL");
        await queryRunner.query("ALTER TABLE `Client` CHANGE `gender` `gender` varchar(15) NULL");
        await queryRunner.query("ALTER TABLE `Client` CHANGE `id_number` `id_number` varchar(20) NULL");
        await queryRunner.query("ALTER TABLE `Client` CHANGE `mothers_maiden_name` `mothers_maiden_name` varchar(150) NULL");
        await queryRunner.query("ALTER TABLE `Client` CHANGE `id_type` `id_type` varchar(15) NULL");
        await queryRunner.query("ALTER TABLE `Client` CHANGE `status` `status` tinyint(1) NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `ClientAssessment` CHANGE `client_id` `client_id` binary(16) NOT NULL");
        // await queryRunner.query("ALTER TABLE `ClientAssessment` ADD UNIQUE INDEX `IDX_9e6d44751031215c43039ae2e2` (`client_id`)");
        await queryRunner.query("ALTER TABLE `ClientAssessment` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `ClientAssessment` CHANGE `fea_category` `fea_category` varchar(20) NULL");
        await queryRunner.query("ALTER TABLE `DefaultUnit` CHANGE `default_id` `default_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `DefaultUnit` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `DefaultUnit` CHANGE `default_id` `default_id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `DefaultUnit` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Department` CHANGE `name` `name` varchar(50) NOT NULL");
        await queryRunner.query("ALTER TABLE `Department` CHANGE `description` `description` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `Document` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `DocumentQueue` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `DocumentUpload` CHANGE `file_name` `file_name` varchar(100) NOT NULL");
        await queryRunner.query("ALTER TABLE `Edd` CHANGE `edd_id` `edd_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `Edd` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `Edd` CHANGE `edd_id` `edd_id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Edd` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Edd` CHANGE `client_name` `client_name` varchar(150) NULL");
        await queryRunner.query("ALTER TABLE `EddCase` CHANGE `case_id` `case_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `EddCase` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `EddCase` CHANGE `case_id` `case_id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `EddCase` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `EddCase` CHANGE `edd_id` `edd_id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `EddCase` CHANGE `edd_count` `edd_count` int NULL DEFAULT '1'");
        await queryRunner.query("ALTER TABLE `EddMaintainable` CHANGE `reason_id` `reason_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `EddMaintainable` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `EddMaintainable` CHANGE `reason_id` `reason_id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `EddMaintainable` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `EddMaintainable` CHANGE `action_type` `action_type` varchar(20) NOT NULL");
        await queryRunner.query("ALTER TABLE `EddModule` CHANGE `module_id` `module_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `EddModule` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `EddModule` CHANGE `module_id` `module_id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `EddModule` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `EddReason` CHANGE `reason_id` `reason_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `EddReason` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `EddReason` CHANGE `reason_id` `reason_id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `EddReason` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        // await queryRunner.query("ALTER TABLE `FpxBank` CHANGE `bank_name` `bank_name` varchar(50) NOT NULL");
        await queryRunner.query("ALTER TABLE `FundAmp` CHANGE `rate_changes` `rate_changes` decimal(10,4) NULL");
        await queryRunner.query("ALTER TABLE `FundDocument` CHANGE `request_id` `request_id` bigint NULL");
        await queryRunner.query("ALTER TABLE `GroupRoleIdList` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Investment` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Investment` CHANGE `client_name` `client_name` varchar(150) NULL");
        await queryRunner.query("ALTER TABLE `Investment` CHANGE `sales_charge` `sales_charge` float(12,4) NULL");
        await queryRunner.query("ALTER TABLE `Investment` CHANGE `ops_exception` `ops_exception` tinyint(1) NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `Investment` CHANGE `request_id` `request_id` bigint NULL");
        await queryRunner.query("ALTER TABLE `Maintainable` CHANGE `type_id` `type_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `Maintainable` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `Maintainable` CHANGE `type_id` `type_id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Maintainable` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `MasterClient` CHANGE `master_client_id` `master_client_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `MasterClient` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `MasterClient` CHANGE `master_client_id` `master_client_id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `MasterClient` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `MasterClient` CHANGE `id_number` `id_number` varchar(20) NULL");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` CHANGE `module_id` `module_id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` CHANGE `question_id` `question_id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `ModuleReason` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `OfficeUser` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `OfficeUser` CHANGE `request_approval_id` `request_approval_id` bigint NULL");
        await queryRunner.query("ALTER TABLE `Options` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Payment` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Question` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Recommendation` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `ReportDocuments` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `RequestApproval` CHANGE `id` `id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `RequestApproval` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `RequestApproval` CHANGE `id` `id` bigint NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `RequestApproval` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `StatusTracker` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `TransactionReason` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `TransactionStatusList` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `UserGroup` CHANGE `description` `description` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `UserGroup` CHANGE `request_approval_id` `request_approval_id` bigint NULL");
        await queryRunner.query("ALTER TABLE `UserGroupIdList` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `UserGroupRole` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `UserRole` CHANGE `description` `description` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `UserRole` CHANGE `request_approval_id` `request_approval_id` bigint NULL");
        await queryRunner.query("ALTER TABLE `UserRole` CHANGE `name` `name` varchar(100) NOT NULL");
        await queryRunner.query("ALTER TABLE `UserRole` CHANGE `status` `status` varchar(20) NULL DEFAULT 'PENDING'");
        await queryRunner.query("ALTER TABLE `UTAccount` CHANGE `MANDT` `MANDT` varchar(10) NULL DEFAULT 'KIB'");
        await queryRunner.query("CREATE UNIQUE INDEX `Agent_UN_3` ON `Agent` (`email`)");
        await queryRunner.query("CREATE UNIQUE INDEX `Agent_UN_2` ON `Agent` (`nric`)");
        await queryRunner.query("CREATE UNIQUE INDEX `Agent_UN_1` ON `Agent` (`agent_id`)");
        await queryRunner.query("CREATE INDEX `Application_IDX_2` ON `Application` (`order_no`)");
        await queryRunner.query("CREATE INDEX `Application_IDX_1` ON `Application` (`agent_id`)");
        await queryRunner.query("CREATE INDEX `AppLog_IDX_1` ON `AppLog` (`username`)");
        await queryRunner.query("CREATE INDEX `AuditLog_IDX_1` ON `AuditLog` (`user_id`)");
        await queryRunner.query("CREATE INDEX `CaseTracker_IDX_2` ON `CaseTracker` (`user_id`)");
        await queryRunner.query("CREATE INDEX `CaseTracker_IDX_1` ON `CaseTracker` (`case_id`)");
        await queryRunner.query("CREATE INDEX `Client_IDX_3` ON `Client` (`master_client_id`)");
        await queryRunner.query("CREATE INDEX `Client_IDX_2` ON `Client` (`id_number`)");
        await queryRunner.query("CREATE INDEX `Client_IDX_1` ON `Client` (`ref_id`)");
        await queryRunner.query("CREATE UNIQUE INDEX `ClientAssessment_UN_1` ON `ClientAssessment` (`client_id`)");
        await queryRunner.query("CREATE INDEX `DefaultUnit_IDX_1` ON `DefaultUnit` (`name`)");
        await queryRunner.query("CREATE INDEX `Department_IDX_1` ON `Department` (`dept_code`)");
        await queryRunner.query("CREATE INDEX `DistributionHistory_IDX_1` ON `DistributionHistory` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `Document_IDX_1` ON `Document` (`client_id`)");
        await queryRunner.query("CREATE INDEX `DocumentQueue_IDX_1` ON `DocumentQueue` (`order_no`)");
        await queryRunner.query("CREATE INDEX `Edd_IDX_3` ON `Edd` (`agent_id`)");
        await queryRunner.query("CREATE INDEX `Edd_IDX_2` ON `Edd` (`uta_id`)");
        await queryRunner.query("CREATE INDEX `Edd_IDX_1` ON `Edd` (`client_id`)");
        await queryRunner.query("CREATE INDEX `EddCase_IDX_4` ON `EddCase` (`agent_id`)");
        await queryRunner.query("CREATE INDEX `EddCase_IDX_3` ON `EddCase` (`client_id`)");
        await queryRunner.query("CREATE INDEX `EddCase_IDX_2` ON `EddCase` (`amla_id`)");
        await queryRunner.query("CREATE INDEX `EddCase_IDX_1` ON `EddCase` (`case_no`)");
        await queryRunner.query("CREATE INDEX `EddMaintainable_IDX_2` ON `EddMaintainable` (`action_type`)");
        await queryRunner.query("CREATE INDEX `EddMaintainable_IDX_1` ON `EddMaintainable` (`category`)");
        await queryRunner.query("CREATE INDEX `EmailBounce_IDX_1` ON `EmailBounce` (`bounce_email`)");
        await queryRunner.query("CREATE INDEX `FundAmp_IDX_1` ON `FundAmp` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `FundDistribution_IDX_1` ON `FundDistribution` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `FundDocument_IDX_1` ON `FundDocument` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `FundHoliday_IDX_1` ON `FundHoliday` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `FundNav_IDX_1` ON `FundNav` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `FundSplit_IDX_1` ON `FundSplit` (`fund_id`)");
        await queryRunner.query("CREATE INDEX `GroupRoleIdList_IDX_2` ON `GroupRoleIdList` (`user_role_id`)");
        await queryRunner.query("CREATE INDEX `GroupRoleIdList_IDX_1` ON `GroupRoleIdList` (`user_group_id`)");
        await queryRunner.query("CREATE INDEX `Investment_IDX_4` ON `Investment` (`agent_id`)");
        await queryRunner.query("CREATE INDEX `Investment_IDX_3` ON `Investment` (`client_id`)");
        await queryRunner.query("CREATE INDEX `Investment_IDX_2` ON `Investment` (`transaction_ref`)");
        await queryRunner.query("CREATE INDEX `Investment_IDX_1` ON `Investment` (`order_no`)");
        await queryRunner.query("CREATE INDEX `Maintainable_IDX_3` ON `Maintainable` (`list_name`)");
        await queryRunner.query("CREATE INDEX `Maintainable_IDX_2` ON `Maintainable` (`type`)");
        await queryRunner.query("CREATE INDEX `Maintainable_IDX_1` ON `Maintainable` (`category`)");
        await queryRunner.query("CREATE INDEX `MasterClient_IDX_1` ON `MasterClient` (`id_number`)");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("DROP INDEX `MasterClient_IDX_1` ON `MasterClient`");
        await queryRunner.query("DROP INDEX `Maintainable_IDX_1` ON `Maintainable`");
        await queryRunner.query("DROP INDEX `Maintainable_IDX_2` ON `Maintainable`");
        await queryRunner.query("DROP INDEX `Maintainable_IDX_3` ON `Maintainable`");
        await queryRunner.query("DROP INDEX `Investment_IDX_1` ON `Investment`");
        await queryRunner.query("DROP INDEX `Investment_IDX_2` ON `Investment`");
        await queryRunner.query("DROP INDEX `Investment_IDX_3` ON `Investment`");
        await queryRunner.query("DROP INDEX `Investment_IDX_4` ON `Investment`");
        await queryRunner.query("DROP INDEX `GroupRoleIdList_IDX_1` ON `GroupRoleIdList`");
        await queryRunner.query("DROP INDEX `GroupRoleIdList_IDX_2` ON `GroupRoleIdList`");
        await queryRunner.query("DROP INDEX `FundSplit_IDX_1` ON `FundSplit`");
        await queryRunner.query("DROP INDEX `FundNav_IDX_1` ON `FundNav`");
        await queryRunner.query("DROP INDEX `FundHoliday_IDX_1` ON `FundHoliday`");
        await queryRunner.query("DROP INDEX `FundDocument_IDX_1` ON `FundDocument`");
        await queryRunner.query("DROP INDEX `FundDistribution_IDX_1` ON `FundDistribution`");
        await queryRunner.query("DROP INDEX `FundAmp_IDX_1` ON `FundAmp`");
        await queryRunner.query("DROP INDEX `EmailBounce_IDX_1` ON `EmailBounce`");
        await queryRunner.query("DROP INDEX `EddMaintainable_IDX_1` ON `EddMaintainable`");
        await queryRunner.query("DROP INDEX `EddMaintainable_IDX_2` ON `EddMaintainable`");
        await queryRunner.query("DROP INDEX `EddCase_IDX_1` ON `EddCase`");
        await queryRunner.query("DROP INDEX `EddCase_IDX_2` ON `EddCase`");
        await queryRunner.query("DROP INDEX `EddCase_IDX_3` ON `EddCase`");
        await queryRunner.query("DROP INDEX `EddCase_IDX_4` ON `EddCase`");
        await queryRunner.query("DROP INDEX `Edd_IDX_1` ON `Edd`");
        await queryRunner.query("DROP INDEX `Edd_IDX_2` ON `Edd`");
        await queryRunner.query("DROP INDEX `Edd_IDX_3` ON `Edd`");
        await queryRunner.query("DROP INDEX `DocumentQueue_IDX_1` ON `DocumentQueue`");
        await queryRunner.query("DROP INDEX `Document_IDX_1` ON `Document`");
        await queryRunner.query("DROP INDEX `DistributionHistory_IDX_1` ON `DistributionHistory`");
        await queryRunner.query("DROP INDEX `Department_IDX_1` ON `Department`");
        await queryRunner.query("DROP INDEX `DefaultUnit_IDX_1` ON `DefaultUnit`");
        await queryRunner.query("DROP INDEX `ClientAssessment_UN_1` ON `ClientAssessment`");
        await queryRunner.query("DROP INDEX `Client_IDX_1` ON `Client`");
        await queryRunner.query("DROP INDEX `Client_IDX_2` ON `Client`");
        await queryRunner.query("DROP INDEX `Client_IDX_3` ON `Client`");
        await queryRunner.query("DROP INDEX `CaseTracker_IDX_1` ON `CaseTracker`");
        await queryRunner.query("DROP INDEX `CaseTracker_IDX_2` ON `CaseTracker`");
        await queryRunner.query("DROP INDEX `AuditLog_IDX_1` ON `AuditLog`");
        await queryRunner.query("DROP INDEX `AppLog_IDX_1` ON `AppLog`");
        await queryRunner.query("DROP INDEX `Application_IDX_1` ON `Application`");
        await queryRunner.query("DROP INDEX `Application_IDX_2` ON `Application`");
        await queryRunner.query("DROP INDEX `Agent_UN_1` ON `Agent`");
        await queryRunner.query("DROP INDEX `Agent_UN_2` ON `Agent`");
        await queryRunner.query("DROP INDEX `Agent_UN_3` ON `Agent`");
        await queryRunner.query("ALTER TABLE `UTAccount` CHANGE `MANDT` `MANDT` varchar(10) NULL");
        await queryRunner.query("ALTER TABLE `UserRole` DROP COLUMN `request_approval_id`");
        await queryRunner.query("ALTER TABLE `UserRole` ADD `request_approval_id` int NULL");
        await queryRunner.query("ALTER TABLE `UserRole` DROP COLUMN `description`");
        await queryRunner.query("ALTER TABLE `UserRole` ADD `description` varchar(100) NOT NULL");
        await queryRunner.query("ALTER TABLE `UserGroupRole` DROP COLUMN `MANDT`");
        await queryRunner.query("ALTER TABLE `UserGroupRole` ADD `MANDT` varchar(30) NOT NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `UserGroupIdList` DROP COLUMN `MANDT`");
        await queryRunner.query("ALTER TABLE `UserGroupIdList` ADD `MANDT` varchar(30) NOT NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `UserGroup` DROP COLUMN `request_approval_id`");
        await queryRunner.query("ALTER TABLE `UserGroup` ADD `request_approval_id` int NULL");
        await queryRunner.query("ALTER TABLE `UserGroup` CHANGE `description` `description` varchar(100) NOT NULL");
        await queryRunner.query("ALTER TABLE `TransactionStatusList` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `TransactionReason` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `StatusTracker` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `RequestApproval` DROP COLUMN `MANDT`");
        await queryRunner.query("ALTER TABLE `RequestApproval` ADD `MANDT` varchar(30) NOT NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `RequestApproval` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `RequestApproval` ADD `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `RequestApproval` ADD PRIMARY KEY (`id`)");
        await queryRunner.query("ALTER TABLE `RequestApproval` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `ReportDocuments` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Recommendation` DROP COLUMN `MANDT`");
        await queryRunner.query("ALTER TABLE `Recommendation` ADD `MANDT` varchar(30) NULL");
        await queryRunner.query("ALTER TABLE `Question` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `Payment` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Options` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `OfficeUser` DROP COLUMN `request_approval_id`");
        await queryRunner.query("ALTER TABLE `OfficeUser` ADD `request_approval_id` int NULL");
        await queryRunner.query("ALTER TABLE `OfficeUser` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `ModuleReason` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` ADD PRIMARY KEY (`module_id`)");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` DROP COLUMN `question_id`");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` ADD `question_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` ADD PRIMARY KEY (`question_id`, `module_id`)");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` ADD PRIMARY KEY (`question_id`)");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` DROP COLUMN `module_id`");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` ADD `module_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` ADD PRIMARY KEY (`module_id`, `question_id`)");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `MasterClient` DROP COLUMN `id_number`");
        await queryRunner.query("ALTER TABLE `MasterClient` ADD `id_number` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `MasterClient` CHANGE `MANDT` `MANDT` varchar(10) NULL");
        await queryRunner.query("ALTER TABLE `MasterClient` DROP COLUMN `master_client_id`");
        await queryRunner.query("ALTER TABLE `MasterClient` ADD `master_client_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `MasterClient` ADD PRIMARY KEY (`master_client_id`)");
        await queryRunner.query("ALTER TABLE `MasterClient` CHANGE `master_client_id` `master_client_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Maintainable` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `Maintainable` DROP COLUMN `type_id`");
        await queryRunner.query("ALTER TABLE `Maintainable` ADD `type_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Maintainable` ADD PRIMARY KEY (`type_id`)");
        await queryRunner.query("ALTER TABLE `Maintainable` CHANGE `type_id` `type_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Investment` DROP COLUMN `request_id`");
        await queryRunner.query("ALTER TABLE `Investment` ADD `request_id` int NULL");
        await queryRunner.query("ALTER TABLE `Investment` CHANGE `ops_exception` `ops_exception` tinyint NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `Investment` CHANGE `sales_charge` `sales_charge` float(12) NULL");
        await queryRunner.query("ALTER TABLE `Investment` DROP COLUMN `client_name`");
        await queryRunner.query("ALTER TABLE `Investment` ADD `client_name` varchar(250) NULL");
        await queryRunner.query("ALTER TABLE `Investment` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `GroupRoleIdList` DROP COLUMN `MANDT`");
        await queryRunner.query("ALTER TABLE `GroupRoleIdList` ADD `MANDT` varchar(30) NOT NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `FundDocument` DROP COLUMN `request_id`");
        await queryRunner.query("ALTER TABLE `FundDocument` ADD `request_id` int NULL");
        await queryRunner.query("ALTER TABLE `FundAmp` CHANGE `rate_changes` `rate_changes` decimal(10,4) NULL");
        // await queryRunner.query("ALTER TABLE `FpxBank` DROP COLUMN `bank_name`");
        // await queryRunner.query("ALTER TABLE `FpxBank` ADD `bank_name` varchar(150) NOT NULL");
        await queryRunner.query("ALTER TABLE `EddReason` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `EddReason` DROP COLUMN `reason_id`");
        await queryRunner.query("ALTER TABLE `EddReason` ADD `reason_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `EddReason` ADD PRIMARY KEY (`reason_id`)");
        await queryRunner.query("ALTER TABLE `EddReason` CHANGE `reason_id` `reason_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `EddModule` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `EddModule` DROP COLUMN `module_id`");
        await queryRunner.query("ALTER TABLE `EddModule` ADD `module_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `EddModule` ADD PRIMARY KEY (`module_id`)");
        await queryRunner.query("ALTER TABLE `EddModule` CHANGE `module_id` `module_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `EddMaintainable` DROP COLUMN `action_type`");
        await queryRunner.query("ALTER TABLE `EddMaintainable` ADD `action_type` varchar(100) NOT NULL");
        await queryRunner.query("ALTER TABLE `EddMaintainable` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `EddMaintainable` DROP COLUMN `reason_id`");
        await queryRunner.query("ALTER TABLE `EddMaintainable` ADD `reason_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `EddMaintainable` ADD PRIMARY KEY (`reason_id`)");
        await queryRunner.query("ALTER TABLE `EddMaintainable` CHANGE `reason_id` `reason_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `EddCase` DROP COLUMN `edd_count`");
        await queryRunner.query("ALTER TABLE `EddCase` ADD `edd_count` bigint NULL DEFAULT '1'");
        await queryRunner.query("ALTER TABLE `EddCase` DROP COLUMN `edd_id`");
        await queryRunner.query("ALTER TABLE `EddCase` ADD `edd_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `EddCase` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `EddCase` DROP COLUMN `case_id`");
        await queryRunner.query("ALTER TABLE `EddCase` ADD `case_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `EddCase` ADD PRIMARY KEY (`case_id`)");
        await queryRunner.query("ALTER TABLE `EddCase` CHANGE `case_id` `case_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Edd` DROP COLUMN `client_name`");
        await queryRunner.query("ALTER TABLE `Edd` ADD `client_name` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `Edd` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `Edd` DROP COLUMN `edd_id`");
        await queryRunner.query("ALTER TABLE `Edd` ADD `edd_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `Edd` ADD PRIMARY KEY (`edd_id`)");
        await queryRunner.query("ALTER TABLE `Edd` CHANGE `edd_id` `edd_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `DocumentUpload` DROP COLUMN `file_name`");
        await queryRunner.query("ALTER TABLE `DocumentUpload` ADD `file_name` varchar(50) NOT NULL");
        await queryRunner.query("ALTER TABLE `DocumentQueue` DROP COLUMN `MANDT`");
        await queryRunner.query("ALTER TABLE `DocumentQueue` ADD `MANDT` varchar(45) NULL DEFAULT 'KIB'");
        await queryRunner.query("ALTER TABLE `Document` CHANGE `MANDT` `MANDT` varchar(10) NULL");
        await queryRunner.query("ALTER TABLE `Department` DROP COLUMN `description`");
        await queryRunner.query("ALTER TABLE `Department` ADD `description` varchar(100) NOT NULL");
        await queryRunner.query("ALTER TABLE `Department` DROP COLUMN `name`");
        await queryRunner.query("ALTER TABLE `Department` ADD `name` varchar(30) NOT NULL");
        await queryRunner.query("ALTER TABLE `DefaultUnit` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `DefaultUnit` DROP COLUMN `default_id`");
        await queryRunner.query("ALTER TABLE `DefaultUnit` ADD `default_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `DefaultUnit` ADD PRIMARY KEY (`default_id`)");
        await queryRunner.query("ALTER TABLE `DefaultUnit` CHANGE `default_id` `default_id` bigint NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `ClientAssessment` DROP COLUMN `fea_category`");
        await queryRunner.query("ALTER TABLE `ClientAssessment` ADD `fea_category` varchar(2) NULL");
        await queryRunner.query("ALTER TABLE `ClientAssessment` CHANGE `MANDT` `MANDT` varchar(10) NULL");
        // await queryRunner.query("ALTER TABLE `ClientAssessment` DROP INDEX `IDX_9e6d44751031215c43039ae2e2`");
        await queryRunner.query("ALTER TABLE `ClientAssessment` CHANGE `client_id` `client_id` binary(16) NOT NULL");
        await queryRunner.query("ALTER TABLE `Client` DROP COLUMN `status`");
        await queryRunner.query("ALTER TABLE `Client` ADD `status` int NULL");
        await queryRunner.query("ALTER TABLE `Client` DROP COLUMN `id_type`");
        await queryRunner.query("ALTER TABLE `Client` ADD `id_type` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `Client` DROP COLUMN `mothers_maiden_name`");
        await queryRunner.query("ALTER TABLE `Client` ADD `mothers_maiden_name` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `Client` DROP COLUMN `id_number`");
        await queryRunner.query("ALTER TABLE `Client` ADD `id_number` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `Client` DROP COLUMN `gender`");
        await queryRunner.query("ALTER TABLE `Client` ADD `gender` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `Client` DROP COLUMN `salutation`");
        await queryRunner.query("ALTER TABLE `Client` ADD `salutation` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `Client` CHANGE `MANDT` `MANDT` varchar(10) NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` DROP COLUMN `max_sales_fee_non_epf`");
        await queryRunner.query("ALTER TABLE `ChargeFee` ADD `max_sales_fee_non_epf` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` DROP COLUMN `min_sales_fee_non_epf`");
        await queryRunner.query("ALTER TABLE `ChargeFee` ADD `min_sales_fee_non_epf` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` DROP COLUMN `max_sales_fee_epf`");
        await queryRunner.query("ALTER TABLE `ChargeFee` ADD `max_sales_fee_epf` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` DROP COLUMN `min_sales_fee_epf`");
        await queryRunner.query("ALTER TABLE `ChargeFee` ADD `min_sales_fee_epf` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` DROP COLUMN `exit_non_epf_percentage`");
        await queryRunner.query("ALTER TABLE `ChargeFee` ADD `exit_non_epf_percentage` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` DROP COLUMN `exit_non_epf_value`");
        await queryRunner.query("ALTER TABLE `ChargeFee` ADD `exit_non_epf_value` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` DROP COLUMN `exit_epf_percentage`");
        await queryRunner.query("ALTER TABLE `ChargeFee` ADD `exit_epf_percentage` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` DROP COLUMN `exit_epf_value`");
        await queryRunner.query("ALTER TABLE `ChargeFee` ADD `exit_epf_value` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `ChargeFee` DROP COLUMN `charge_fee_id`");
        await queryRunner.query("ALTER TABLE `ChargeFee` ADD `charge_fee_id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `ChargeFee` ADD PRIMARY KEY (`charge_fee_id`)");
        await queryRunner.query("ALTER TABLE `ChargeFee` CHANGE `charge_fee_id` `charge_fee_id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `CaseTracker` DROP COLUMN `remark`");
        await queryRunner.query("ALTER TABLE `CaseTracker` ADD `remark` varchar(300) NULL");
        await queryRunner.query("ALTER TABLE `CaseTracker` DROP COLUMN `case_id`");
        await queryRunner.query("ALTER TABLE `CaseTracker` ADD `case_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `CaseTracker` CHANGE `MANDT` `MANDT` varchar(10) NOT NULL");
        await queryRunner.query("ALTER TABLE `Branch` CHANGE `timestamp` `timestamp` bigint NULL");
        await queryRunner.query("ALTER TABLE `Branch` DROP COLUMN `code`");
        await queryRunner.query("ALTER TABLE `Branch` ADD `code` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `Branch` DROP COLUMN `state`");
        await queryRunner.query("ALTER TABLE `Branch` ADD `state` varchar(100) NULL");
        await queryRunner.query("ALTER TABLE `Branch` CHANGE `MANDT` `MANDT` varchar(10) NULL");
        await queryRunner.query("ALTER TABLE `AuditLog` DROP COLUMN `request_id`");
        await queryRunner.query("ALTER TABLE `AuditLog` ADD `request_id` int NULL");
        await queryRunner.query("ALTER TABLE `Application` CHANGE `uta_id` `uta_id` binary(16) NOT NULL");
        await queryRunner.query("ALTER TABLE `Agent` CHANGE `timestamp` `timestamp` bigint NULL");
        await queryRunner.query("ALTER TABLE `Agent` DROP COLUMN `agency`");
        await queryRunner.query("ALTER TABLE `Agent` ADD `agency` varchar(50) NULL");
        // await queryRunner.query("ALTER TABLE `Agent` DROP INDEX `IDX_bd0aac431ed1187ca6d1fb60a8`");
        await queryRunner.query("ALTER TABLE `Agent` CHANGE `nric` `nric` varchar(16) NOT NULL");
        await queryRunner.query("ALTER TABLE `Agent` DROP COLUMN `agent_code`");
        await queryRunner.query("ALTER TABLE `Agent` ADD `agent_code` varchar(50) NULL");
        await queryRunner.query("ALTER TABLE `Agent` DROP COLUMN `MANDT`");
        await queryRunner.query("ALTER TABLE `Agent` ADD `MANDT` varchar(30) NULL");
        // await queryRunner.query("ALTER TABLE `Agent` DROP INDEX `IDX_04bbcf1b15f36b382c0aa749c2`");
        await queryRunner.query("ALTER TABLE `Agent` CHANGE `agent_id` `agent_id` binary(16) NOT NULL");
        await queryRunner.query("ALTER TABLE `FundHoliday` DROP COLUMN `name`");
        // await queryRunner.query("ALTER TABLE `FundDocument` DROP COLUMN `file_type`");
        await queryRunner.query("ALTER TABLE `DefaultUnit` DROP COLUMN `display_name`");
        await queryRunner.query("CREATE INDEX `ModuleQuestion_FK` ON `ModuleQuestion` (`question_id`)");
        await queryRunner.query("CREATE INDEX `master_client_id` ON `MasterClient` (`master_client_id`)");
        await queryRunner.query("CREATE INDEX `Investment_FK_2` ON `Investment` (`order_no`)");
        await queryRunner.query("CREATE INDEX `Investment_FK_1` ON `Investment` (`client_id`)");
        await queryRunner.query("CREATE UNIQUE INDEX `EddCase_UN` ON `EddCase` (`case_no`)");
        await queryRunner.query("CREATE INDEX `EddCase_FK_5` ON `EddCase` (`uta_id`)");
        await queryRunner.query("CREATE INDEX `EddCase_FK_4` ON `EddCase` (`edd_id`)");
        await queryRunner.query("CREATE INDEX `EddCase_FK_2` ON `EddCase` (`agent_id`)");
        await queryRunner.query("CREATE INDEX `EddCase_FK_1` ON `EddCase` (`client_id`)");
        await queryRunner.query("CREATE INDEX `EddCase_FK` ON `EddCase` (`amla_id`)");
        await queryRunner.query("CREATE INDEX `Edd_FK_3` ON `Edd` (`uta_id`)");
        await queryRunner.query("CREATE INDEX `Edd_FK_2` ON `Edd` (`agent_id`)");
        await queryRunner.query("CREATE INDEX `Edd_FK` ON `Edd` (`client_id`)");
        await queryRunner.query("CREATE INDEX `doct_id` ON `Document` (`document_id`)");
        await queryRunner.query("CREATE INDEX `doc_client_id` ON `Document` (`client_id`)");
        await queryRunner.query("CREATE INDEX `risk_score` ON `ClientAssessment` (`risk_score`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_9e6d44751031215c43039ae2e2` ON `ClientAssessment` (`client_id`)");
        await queryRunner.query("CREATE UNIQUE INDEX `client_id_UNIQUE` ON `ClientAssessment` (`client_id`)");
        await queryRunner.query("CREATE INDEX `client_id` ON `ClientAssessment` (`client_id`)");
        await queryRunner.query("CREATE INDEX `joint_client_fk_idx` ON `Client` (`ref_id`)");
        await queryRunner.query("CREATE INDEX `client_id_fk` ON `Client` (`client_id`)");
        await queryRunner.query("CREATE INDEX `CaseTracker_FK_1` ON `CaseTracker` (`user_id`)");
        await queryRunner.query("CREATE INDEX `CaseTracker_FK` ON `CaseTracker` (`case_id`)");
        await queryRunner.query("CREATE UNIQUE INDEX `fa_code_UNIQUE` ON `Agent` (`fa_code`)");
        await queryRunner.query("CREATE UNIQUE INDEX `Email_UN` ON `Agent` (`email`)");
        await queryRunner.query("CREATE UNIQUE INDEX `agent_id_UNIQUE` ON `Agent` (`agent_id`)");
        await queryRunner.query("ALTER TABLE `UTAccount` ADD CONSTRAINT `FK_e6d3bf66e5a97fc5adac7f4ffb2` FOREIGN KEY (`joint_id`) REFERENCES `Client`(`client_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `Payment` ADD CONSTRAINT `FK_9c6d107c5e1ddb80e81b821b179` FOREIGN KEY (`agent_id`) REFERENCES `Agent`(`agent_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `Payment` ADD CONSTRAINT `FK_823c82b9e2ce11ccad66e36b2ce` FOREIGN KEY (`doc_id`) REFERENCES `Document`(`document_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `OfficeUser` ADD CONSTRAINT `FK_3c6be3e17ee091aefcbf119d46e` FOREIGN KEY (`user_group_role_id`) REFERENCES `UserGroupRole`(`user_group_role_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `ModuleReason` ADD CONSTRAINT `FK_fa3cad0cd2a73b35cf1b940ddc8` FOREIGN KEY (`reason_id`) REFERENCES `EddReason`(`reason_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `ModuleReason` ADD CONSTRAINT `FK_0169d301a545068bc54016bad34` FOREIGN KEY (`module_id`) REFERENCES `EddModule`(`module_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` ADD CONSTRAINT `FK_a4c066f2a6fdf44dd02e6c0660b` FOREIGN KEY (`module_id`) REFERENCES `EddModule`(`module_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `ModuleQuestion` ADD CONSTRAINT `FK_037a4d901b8cd5067bb1401d1b3` FOREIGN KEY (`question_id`) REFERENCES `Question`(`question_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `Investment` ADD CONSTRAINT `FK_e9f1de495fc04601028b81a6bf2` FOREIGN KEY (`client_id`) REFERENCES `Client`(`client_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `EddCase` ADD CONSTRAINT `FK_cd3b4f4ea7bc0dea21c9dd28cea` FOREIGN KEY (`agent_id`) REFERENCES `Agent`(`agent_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `EddCase` ADD CONSTRAINT `FK_8f98dc8bf3579c4c1be800cb96d` FOREIGN KEY (`uta_id`) REFERENCES `UTAccount`(`uta_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `EddCase` ADD CONSTRAINT `FK_4ed223c8a4beb795e0b19dc185b` FOREIGN KEY (`amla_id`) REFERENCES `OfficeUser`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE");
        await queryRunner.query("ALTER TABLE `EddCase` ADD CONSTRAINT `FK_31382fce5e0b940da02602f453c` FOREIGN KEY (`client_id`) REFERENCES `Client`(`client_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `EddCase` ADD CONSTRAINT `FK_0a8a3c2b9543efbb396f5e930e1` FOREIGN KEY (`edd_id`) REFERENCES `Edd`(`edd_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `Edd` ADD CONSTRAINT `FK_a0bbbc43b70b5b3120efb9d4287` FOREIGN KEY (`client_id`) REFERENCES `Client`(`client_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `Edd` ADD CONSTRAINT `FK_95fb95debbf9a58635ad43ae164` FOREIGN KEY (`agent_id`) REFERENCES `Agent`(`agent_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `Edd` ADD CONSTRAINT `FK_7a21ad29d65d05eb9e2e0a4451e` FOREIGN KEY (`uta_id`) REFERENCES `UTAccount`(`uta_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `Document` ADD CONSTRAINT `FK_610236cf8c9a02e9d17f9f95029` FOREIGN KEY (`client_id`) REFERENCES `Client`(`client_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `ClientAssessment` ADD CONSTRAINT `FK_9e6d44751031215c43039ae2e23` FOREIGN KEY (`client_id`) REFERENCES `Client`(`client_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `Client` ADD CONSTRAINT `FK_54aea71963d14571999cfe0c9f1` FOREIGN KEY (`ref_id`) REFERENCES `Client`(`client_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
        await queryRunner.query("ALTER TABLE `CaseTracker` ADD CONSTRAINT `FK_90c445a2765f361ee0cc39ad8e0` FOREIGN KEY (`case_id`) REFERENCES `EddCase`(`case_id`) ON DELETE RESTRICT ON UPDATE RESTRICT");
    }

}
